INSERT INTO responses values(0 ,0, 'os', 'mac');
INSERT INTO responses values(0 ,1, 'os', 'windows');
INSERT INTO responses values(0 ,2, 'os', 'linux');
INSERT INTO responses values(1 ,3, 'gender', 'male');
INSERT INTO responses values(1 ,4, 'gender', 'female');
INSERT INTO contingency values(0, 3, 10);
INSERT INTO contingency values(0, 4, 20);
INSERT INTO contingency values(1, 3, 30);
INSERT INTO contingency values(1, 4, 5);
INSERT INTO contingency values(2, 3, 12);
INSERT INTO contingency values(2, 4, 53);
INSERT INTO contingency values(3, 0, 10);
INSERT INTO contingency values(4, 0, 20);
INSERT INTO contingency values(3, 1, 30);
INSERT INTO contingency values(4, 1, 5);
INSERT INTO contingency values(3, 2, 12);
INSERT INTO contingency values(4, 2, 53);